include/bitcoin/bitcoin/math/ec_keys.hpp
src/math/ec_keys.cpp
src/script.cpp
src/wallet/message.cpp
test/ec_keys.cpp

The previous implementation didn't provide any way to try a different
nonce if the signature is invalid.

Improve rfc6979 compatibility

---

src/Makefile.am

Fix building when libsecp256k1 is not in the default path.
(continues from https://github.com/libbitcoin/libbitcoin/pull/172)
Found! :)
FYI:
libsecp256k1_LIBS='-L/home/sx/sx/lib -lsecp256k1  '

[build] Use libsecp256k1_LIBS flag

---

include/bitcoin/bitcoin/constants.hpp

For some strange reason I get this compile error on Debian.
CXX    src/network/src_libbitcoin_la-network.lo
In file included from ./include/bitcoin/bitcoin/satoshi_serialize.hpp:24:0,
from ./include/bitcoin/bitcoin/network/channel.hpp:36,
from src/network/channel.cpp:20:
./include/bitcoin/bitcoin/constants.hpp:84:33: error: 'UINTPTR_MAX' was not declared in this scope
In file included from ./include/bitcoin/bitcoin/satoshi_serialize.hpp:24:0,
from ./include/bitcoin/bitcoin/network/channel.hpp:36,
from src/network/handshake.cpp:26:
./include/bitcoin/bitcoin/constants.hpp:84:33: error: 'UINTPTR_MAX' was not declared in this scope
make: *** [src/network/src_libbitcoin_la-handshake.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/network/src_libbitcoin_la-channel.lo] Error …

Added fix for compile error on Debian.

---

include/bitcoin/bitcoin/network/channel.hpp
src/network/channel.cpp

Basically the stopped_ variable exists to avoid code which closes the socket and calls the handlers from being called twice.
Since the stop_impl() code may be called by different threads, it can happen that the code gets executed eventhough the check at the beginning [if (stopped_) return...] passes. This fixes that by adding a mutex.

Fix race condition in channel

---

configure.ac
libbitcoin.pc.in

Thanks @genjix for the suggestion. This guarantees consistency with dependency builds and simplifies their configure.ac.

ENABLE_TESTNET propagation through pc.in.

---

Makefile.am
builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj
builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj.filters
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/formats/base64.hpp
include/bitcoin/bitcoin/formats/base85.hpp
src/formats/base64.cpp
src/formats/base85.cpp
test/base85.cpp

This is the native format for CurveZMQ certificates, which we use in server and bx.

Add base85 (Z85) format for client/server certificates.

---

src/utility/binary.cpp
test/binary.cpp

Additionally, added test for validation.

Correct default parameter behavior on get_substring

---

include/bitcoin/bitcoin/primitives.hpp
src/network/channel.cpp

These clients send ping messages with 0-length payloads. would kill the connection immediately, we were checking message sizes in the header validator. The message validator should not be checking these things; that a job for satoshi_load.
This is a workaround for issue libbitcoin/libbitcoin-server#50. The full solution will take more work, but I have left a TODO in the appropriate place. With this patch, we are at least able to connect to the network and download blocks in a semi-fast manner.

Allow connections to Satoshi 0.10 clients

---

m4/ax_boost_chrono.m4

the file is part of GNU autoconf, taken from https://www.gnu.org/software/autoconf-archive/ax_boost_chrono.html

missing m4 for autoconf detection of boost_chrono libs

---

include/bitcoin/bitcoin/math/hash.hpp
include/bitcoin/bitcoin/wallet/dictionary.hpp
include/bitcoin/bitcoin/wallet/mnemonic.hpp
src/math/external/pkcs5_pbkdf2.c
src/math/external/pkcs5_pbkdf2.h
src/math/hash.cpp
src/wallet/dictionary.cpp
src/wallet/mnemonic.cpp
test/hash.cpp
test/mnemonic.cpp
test/mnemonic.hpp

This is an update on pull request #234. Here are the fixes:
* Remove the unnecessary pbkdf2 assertions.
* Expose the built-in dictionaries as a std::map for run-time string-based lookup.
* Rename `wordlist` to `dictionary`, as requested.
I expose the built-in dictionaries two ways, once as plain C++ variables and again through a string-based std::map. If a developer knows which language they want at compile-time, they can simply refer to the plain variables. This removes the indirection of an enum, and makes the compile-time language lookup a lot simpler. Its main users are default parameters and unit tests, so I would be willing to privatize this capability if necessary.
For run-time language lookup, the developer can examine the map to determine which languages are available. The …

Mnemonic clean-up, second try

---

README.md

A minor README.md fix I just bumped into while building libbitcoin. Since [this](https://github.com/libbitcoin/libbitcoin/commit/19b6e4503f00c02984a48a0435bad6ac4947f58b#diff-3fbb47e318cd8802bd325e7da9aaabe8R532) the build script builds from 'version3' branch of secp256k1.

Fix doc about the branch secp256k1 is built from

---

Makefile.am
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/network/acceptor.hpp
include/bitcoin/bitcoin/network/channel.hpp
include/bitcoin/bitcoin/network/channel_loader_module.hpp
include/bitcoin/bitcoin/network/channel_proxy.hpp
include/bitcoin/bitcoin/network/channel_stream_loader.hpp
include/bitcoin/bitcoin/network/handshake.hpp
include/bitcoin/bitcoin/network/hosts.hpp
include/bitcoin/bitcoin/network/protocol.hpp
include/bitcoin/bitcoin/utility/data.hpp
src/network/acceptor.cpp
src/network/channel.cpp
src/network/channel_proxy.cpp
src/network/channel_stream_loader.cpp
src/network/connect_with_timeout.cpp
src/network/connect_with_timeout.hpp
src/network/handshake.cpp
src/network/hosts.cpp
src/network/network.cpp

We have been moving the libraries towards a "one class per file" organization. I've applied this to the network namespace in order to make that layer easier to traverse, as we troubleshoot network/chain/node blocking issues.

Factor network files into class-per-file organization.

---

include/bitcoin/bitcoin/constants.hpp
include/bitcoin/bitcoin/error.hpp
include/bitcoin/bitcoin/network/channel.hpp
include/bitcoin/bitcoin/network/channel_loader_module.hpp
include/bitcoin/bitcoin/network/channel_proxy.hpp
include/bitcoin/bitcoin/network/channel_stream_loader.hpp
include/bitcoin/bitcoin/network/protocol.hpp
include/bitcoin/bitcoin/network/seeder.hpp
include/bitcoin/bitcoin/network/settings.hpp
include/bitcoin/bitcoin/network/timeout.hpp
include/bitcoin/bitcoin/utility/subscriber.hpp
src/error.cpp
src/network/acceptor.cpp
src/network/channel.cpp
src/network/channel_proxy.cpp
src/network/channel_stream_loader.cpp
src/network/connect_with_timeout.cpp
src/network/connect_with_timeout.hpp
src/network/handshake.cpp
src/network/protocol.cpp
src/network/seeder.cpp
src/network/timeout.cpp

Eliminate macros, stack allocate subscribers, use `std::map` for loader modules, replace "slots" mechanism, use `std::find` vs. loops, use `async_parallel` for seeder completion, simplify `protocol` logging, implement all `version` object sizes, add support and configuration for `version.relay`, implement full `ping` and `pong` support with validation and loopback detection, bypass seeding when host pool is empty, add relay and retries options to `maintain_connection`. Fix handshake timeout regression.

Networking fixes and enhancements.

---

include/bitcoin/bitcoin/formats/base16.hpp
src/formats/base10.cpp
src/formats/base16.cpp
src/wallet/uri.cpp
test/chain/script.cpp

The C standard library character classification functions depend
on the current locale, and can give crazy answers in some situations.
Provide our own is_base16 function that unambiguously corresponds
to the valid character range for that format.

Fix base16 locale dependency issues

---

include/bitcoin/bitcoin/wallet/bitcoin_uri.hpp
include/bitcoin/bitcoin/wallet/uri.hpp
src/wallet/bitcoin_uri.cpp
src/wallet/uri.cpp
test/wallet/bitcoin_uri.cpp
test/wallet/uri.cpp

Overall looks great, found a couple of extra copies, but no material issues just minor style.
* Place [member variables](https://github.com/libbitcoin/libbitcoin/blob/master/style_guide.md#hpp-format) below methods in class declaration.
* Don't treat non-Boolean values or expressions as Boolean.
* For example `if (!foo.size()) ...` and `if (foo.compare(0, 4, "req-")) ...`.
* Try to name out parameters using `out` or `out_` prefix.
* Avoid making changes to out parameters unless the result is successful.
* Place out parameters on left.
* This avoids the conflict that occurs with defaulted parameters, which can only go on the right, forcing out parameters to the middle.
* Use `const` and `auto` wherever possible unless there's a compelling readability reason.
* Minimize use of `this->` …

Review of new bitcoin uri implementation.

---

include/bitcoin/bitcoin/wallet/bitcoin_uri.hpp
include/bitcoin/bitcoin/wallet/uri_reader.hpp
src/wallet/bitcoin_uri.cpp
src/wallet/uri.cpp
test/wallet/bitcoin_uri.cpp
test/wallet/uri_reader.cpp

This creates a unified reader-writer based on the scheme-agnostic `uri`.
The `uri_parse` function has been templatized to resolve the problem of returning a partially-initialized URI in the failure case. It has also been moved statically into `uri_reader`, as it accepts a reader as its template (formerly out) parameter.
Bitcoin semantics have been removed from the general purpose parse function by incorporating them into the visitor (implemented by the `bitcoin_uri`). The `uri_reader` interface is expanded to require full general  parsing callbacks, allowing it to support any uri scheme.
The unified reader-writer hides all properties behind accessors in order to maintain consistent state. This was easier without using optional return values, and is generally easier to access, but it …

bitcoin_uri reader-writer based on new interface/parser

---

include/bitcoin/bitcoin/wallet/address.hpp

The Airbitz wallet is seeing bad performance when we use bc::payment_address
with std::unordered_map. This change speeds things up about 3x.

Speed up the payment_address hash function

---

include/bitcoin/bitcoin/constants.hpp
include/bitcoin/bitcoin/script.hpp
src/script.cpp

Libbitcoin has previously relied on hardcoded heights (for testnet and mainnet) to determine consensus softfork activation and enforcement. These have been incomplete and not fully-constraining validation in the activation ranges. This is more problematic and complex in the midst of a soft fork than the full/proper implementation. These are also potentially invalidated in the case of a deep reorg. This work will activate according to the various BIP specifications, currently BIP16/30/34/66/65.

Modify "switchover heights" for proper activation measurement.

---

Makefile.am
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/impl/utility/resubscriber.ipp
include/bitcoin/bitcoin/network/channel_proxy.hpp
include/bitcoin/bitcoin/network/handshake.hpp
include/bitcoin/bitcoin/network/protocol.hpp
include/bitcoin/bitcoin/network/seeder.hpp
include/bitcoin/bitcoin/utility/resubscriber.hpp
include/bitcoin/bitcoin/utility/subscriber.hpp
src/network/channel_proxy.cpp
src/network/handshake.cpp
src/network/protocol.cpp
src/network/seeder.cpp

This fixes a longstanding race condition in message receipt. Unhandled blocks, as a result of this issue, regularly cause the appearance of orphans. This causes re-requesting of blocks as well as frequent costly reorgs. Eventually the message backlog overloads the node's memory.

Move all message subscriptions to resubscriber template.

---

include/bitcoin/bitcoin/define.hpp
src/utility/threadpool.cpp

This is primarily to simplify trivial API usage.

Prevent threadpool destruct without join.

---

include/bitcoin/bitcoin/wallet/select_outputs.hpp

I opted to make this a struct, but we could alternatively declare what's inside public.  Usage is disallowed otherwise and assuming that's not intended since it's useful.

Make static class members public

---

include/bitcoin/bitcoin/wallet/hd_public.hpp

Library builds and links fine. `make check` passes.

Remove unimplemented hd_lineage::operator< definition.

---

include/bitcoin/bitcoin/impl/utility/endian.ipp

Does not appear to address any existing big endian issues, however is necessary for endian related functionality provided by endian.hpp to be platform independent.

Alter stream.read() use related to endianness.

---

include/bitcoin/bitcoin/chain/script/operation.hpp
include/bitcoin/bitcoin/math/elliptic_curve.hpp
include/bitcoin/bitcoin/wallet/stealth_address.hpp
src/chain/script/operation.cpp
src/wallet/stealth_address.cpp

Switched code to use typedefs which is improves code readability.

Always typedef templated types such as std::vector

---

include/bitcoin/bitcoin/message/block_message.hpp
include/bitcoin/bitcoin/message/transaction_message.hpp
src/chain/block.cpp
src/message/block_message.cpp
src/message/transaction_message.cpp

This provides simple temporary relief for a node break. Previously block/tx messages were passed via non-const pointers and could thus be modified without compiler complaint. Now that they are correctly const this issue is exposed (i.e. not new). Because these messages are handled via public subscription they must not be modified in an unsafe manner. In order to be both safe and correct, this message must be handled by the implementation before any other subscribers receive it.

HACK: make set_originator() const.

---

include/bitcoin/bitcoin/chain/script/script.hpp
src/chain/script/operation.cpp
src/chain/script/script.cpp
test/chain/script.cpp

Addresses libbitcoin/libbitcoin-server#143, an error introduced in serialization rewrite along with the issue present prior to rewrite.
TODO: remove the opcode entirely - I have not tracked down whether it is in use external to this repo.

Remove opcode::raw_data dependence in parsing.

---

include/bitcoin/bitcoin/chain/output_point.hpp
src/chain/output_point.cpp

Currently I cannot create a pointer of the libbitcoin::chain::output_point::validation* type because there is a value in that class with the same name and the compiler gets confused. This pull request renames the type with a suffix so it can be specified.

Rename output_point::validation to validation_type

---

include/bitcoin/bitcoin/utility/threadpool.hpp
src/utility/threadpool.cpp

This does not fix a problem, it is intended to help isolate a troublesome network failure.

Add logging for threadpool self-join and unjoinable.

---

Makefile.am
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/wallet/stealth.hpp
src/wallet/stealth.cpp
test/wallet/stealth.cpp

Unit test is also included. Example usage:
// Receiver
// -----------------------------------
// ...
stealth_receiver receiver(scan_private, spend_private);
const stealth_address stealth_addr = receiver.generate_stealth_address();
// Sender
// -----------------------------------
stealth_sender sender();
sender.send_to_stealth_address(stealth_addr);
// Make new tx with these outputs:
//   sender.meta_script()
//   sender.send_address()
// client.fetch_stealth() returns ephemeral_public
// derived from meta_script output.
// Receiver
// -----------------------------------
// Now the receiver should be able to regenerate the send_address
// using just the ephemeral_public.
const auto derived_address = receiver.derive_address(ephemeral_public);
if (derived_address == actual_address)
{
// …

Added stealth_receiver and stealth_sender classes for stealth

---

include/bitcoin/bitcoin/chain/transaction.hpp
src/chain/transaction.cpp

Reverting because the performance advantage is minimal and not worth the extra code.

Revert: cache raw data on wire to_data and hash method calls. 

---

Makefile.am
builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj
builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj.filters
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/message/alert.hpp
include/bitcoin/bitcoin/message/alert_payload.hpp
include/bitcoin/bitcoin/message/heading.hpp
include/bitcoin/bitcoin/message/messages.hpp
src/message/alert.cpp
src/message/alert_payload.cpp
src/message/heading.cpp
test/message/alert.cpp
test/message/alert_payload.cpp
test/message/heading.cpp

There are way too many old peers forwarding alerts now that Core has published the private key.

Revert alert removal.

---

README.md

While trying to install libbitcoin on Macintosh and Ubuntu for experimenting, I overlooked the important build notes that were effectively buried after the MacPorts install procedure.
This PR mainly changes the Notes heading to 'Build Notes for Linux / macOS' and raises it to H3 level, same as the main platform headings. It then adds reference links to the build notes next to the install statements for Linux, Homebrew, and MacPorts, so the user is aware of the detailed build notes and can go there easily. It also adds a direct link to the `install.sh` script at the top of the notes, before the discussion of specific options.
It adds a link to the wiki documentation parallel to the links already in the libbitcoin-explorer and libbitcoin-server READMEs.
It replaces the detailed install …

Tweaks to README organization & OS X rename

---

include/bitcoin/bitcoin/chain/block.hpp
include/bitcoin/bitcoin/chain/output_point.hpp
include/bitcoin/bitcoin/chain/point.hpp
include/bitcoin/bitcoin/chain/transaction.hpp
include/bitcoin/bitcoin/error.hpp
src/chain/block.cpp
src/chain/output_point.cpp
src/chain/point.cpp
src/chain/transaction.cpp
src/error.cpp
test/chain/transaction.cpp

This is a performance optimization for blockchain and also implements a stubbed-in utility method. This also moves this part of validation into the context-free block.check, allowing for earlier rejection of invalid blocks and fixes incorrect return in the API (i.e. standalone) use of block.check.
It also provides a tx pool guard against accepting internally-double-spending txs. This was previously guarded only by block validation (which included pre-validated txs). The benefit is in preventing storage and relay of provably invalid (though unconfirmed) txs.

Move internal double-spend check from blockchain:: to chain::

---

include/bitcoin/bitcoin/chain/chain_state.hpp
include/bitcoin/bitcoin/constants.hpp
src/chain/chain_state.cpp

This is a consensus bug in the case where a final checkpoint precedes a soft fork activation height by less than potentially 2016 blocks (testnet) or 1000 blocks (mainnet).

Fix/remove chain_state checkpoint use, allow promotion in all cases.

---

README.md

Homebrew now has a libbitcoin formula. libbitcoin can be installed simply by calling `brew install libbitcoin`. By default, Homebrew installs libbitcoin from a "bottle" without building. It can also be built from source if desired.
The forumla installs boost as a dependency. The formula also builds libbitcoin/secp256k1 as a "resource." Because this repo is a fork, homebrew will not allow it to be added as a formula. This installs secp256k1 in libbitcoin's "cellar" at `/usr/local/Cellar/libbitcoin/3.3.0/libexec`, but not in the system at `/usr/local/lib`. Until the upstream repo adds a tagged release, we have to use this workaround.
Feel free to review the [formula pull request](https://github.com/Homebrew/homebrew-core/pull/16771) and provide feedback.
```
==> Installing dependencies for …
```

Update homebrew section to use libbitcoin formula

---

include/bitcoin/bitcoin/chain/script.hpp
include/bitcoin/bitcoin/impl/machine/interpreter.ipp
include/bitcoin/bitcoin/impl/machine/operation.ipp
include/bitcoin/bitcoin/machine/script_pattern.hpp
include/bitcoin/bitcoin/math/elliptic_curve.hpp
src/chain/script.cpp
src/math/elliptic_curve.cpp
src/math/stealth.cpp
src/wallet/payment_address.cpp
test/chain/script.cpp

This revises script address extraction and adds detailed comments regarding the limitations of context-free address extraction from input scripts. It also reverts keys->addresses extraction from bare multisig. Finally null_data is renamed to pay_null_data in order to match the existing naming conventions for output scripts.

Revise script address extraction.

---

include/bitcoin/bitcoin/chain/block.hpp
include/bitcoin/bitcoin/constants.hpp
src/chain/block.cpp
src/chain/chain_state.cpp

This PR adds everything required to run libbitcoin on the regtest network as described by @evoskuil in the issue https://github.com/libbitcoin/libbitcoin-server/issues/404. This includes adding the encoded regtestnet genesis block, updated proof of work limit, and work required calculation. 
All of these changed are protected by the `WITH_REGTEST` flag, except `encoded_regtestnet_genesis_block` and `genesis_regtestnet ` which are namespaced.
This PR doesn't implement any makefile changes. Adding `#define WITH_REGTEST` near the top of `include/bitcoin/bitcoin/constants.hpp` works as a temporary workaround.

Regtest network support

---

include/bitcoin/bitcoin/chain/block.hpp
include/bitcoin/bitcoin/chain/header.hpp
include/bitcoin/bitcoin/chain/transaction.hpp
include/bitcoin/bitcoin/config/settings.hpp
include/bitcoin/bitcoin/constants.hpp
include/bitcoin/bitcoin/machine/rule_fork.hpp
src/chain/block.cpp
src/chain/chain_state.cpp
src/chain/header.cpp
src/chain/transaction.cpp
test/chain/block.cpp
test/chain/compact.cpp
test/chain/header.cpp
test/formats/base_10.cpp

The ~`retarget` (regtest) flag takes precedence for proof of work in the case of conflict with the `easy_blocks` (testnet) flag.

Complete and parameterize regtest implementation.

---

include/bitcoin/bitcoin/machine/sighash_algorithm.hpp
src/chain/script.cpp

The existing implementation fails to mask the sighash byte when extracting the enumeration.

CONSENSUS: patch sighash type extraction.

---

src/chain/script.cpp

This is a vector read safety issue but otherwise does not affect the terminating condition.

Prevent iteration past end in findanddelete increment.

---

include/bitcoin/bitcoin/wallet/electrum.hpp
test/wallet/electrum.cpp

Require dictionary for electrum mnemonic validation when specific dictionary is used to avoid ambiguous call when any dictionary can be checked
Lowercase electrum entropy test inputs
Add a non-english electrum mnemonic test

Electrum test updates

---

include/bitcoin/bitcoin/math/elliptic_curve.hpp
src/math/elliptic_curve.cpp
test/math/elliptic_curve.cpp

Provided unit test.
Neccessary for modern privacy schemes which hide sharing amounts. They involve summing points from different curves together: A + B + C. This function provides that functionality.

added new function to math/ called ec_sum. Adds a list of provided ec points together.

---

include/bitcoin/bitcoin/utility/timer.hpp

Changed buffer size to 25, to include the terminating null-character.

[linux] log startup does not display local date/times. #788

---

include/bitcoin/bitcoin/utility/property_tree.hpp
src/utility/property_tree.cpp
test/utility/property_tree.cpp

Avoid suppressing errors when converting json strings to property trees by returning a bool to indicate success/failure.

Avoid suppressing errors when converting json strings

---

Makefile.am
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/impl/utility/serializer.ipp
include/bitcoin/bitcoin/math/elliptic_curve.hpp
include/bitcoin/bitcoin/math/ring_signature.hpp
include/bitcoin/bitcoin/utility/ostream_writer.hpp
include/bitcoin/bitcoin/utility/serializer.hpp
include/bitcoin/bitcoin/utility/writer.hpp
src/math/elliptic_curve.cpp
src/math/ring_signature.cpp
src/utility/ostream_writer.cpp
test/math/ring_signature.cpp
test/math/ring_signature_vectors.hpp

This adds Borromean ring signatures. The unit test is exactly the same as the experimental secp256k1-zkp branch. I will spend more time verifying and auditing this code, but it will also require some review by an outsider. I'm confident the code is better written and more understandable, more condensed than the secp256k1-zkp code. I tried to keep the interface design similar to ec sign/verify but there are some subtle differences, namely that the message digest is computed by hashing it together with the signing keys and done internally in the code.

Ring signature

---

src/unicode/unicode_streambuf.cpp

@pmienk This was introduced in the warnings fix. It would only be caught in the MSVC test run.

Fix MSVC unicode stream regression.

---

include/bitcoin/bitcoin/impl/utility/string.ipp
include/bitcoin/bitcoin/unicode/console_streambuf.hpp
src/chain/compact.cpp
src/chain/transaction.cpp
src/math/elliptic_curve.cpp
src/unicode/console_streambuf.cpp
src/unicode/unicode.cpp
src/unicode/unicode_istream.cpp
src/unicode/unicode_ostream.cpp
src/wallet/encrypted_keys.cpp
test/wallet/encrypted_keys.cpp

@thecodefactory Please review [remaining warnings](https://travis-ci.org/libbitcoin/libbitcoin/builds/401945319) from PNG and QRCode.

Fix deserialize trim param, clean up new warnings.

---

Makefile.am
builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj
builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj.filters
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
builds/msvc/vs2015/libbitcoin-test/libbitcoin-test.vcxproj
builds/msvc/vs2015/libbitcoin-test/libbitcoin-test.vcxproj.filters
builds/msvc/vs2015/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2015/libbitcoin/libbitcoin.vcxproj.filters
builds/msvc/vs2017/libbitcoin-test/libbitcoin-test.vcxproj
builds/msvc/vs2017/libbitcoin-test/libbitcoin-test.vcxproj.filters
builds/msvc/vs2017/libbitcoin/libbitcoin.vcxproj
builds/msvc/vs2017/libbitcoin/libbitcoin.vcxproj.filters
include/bitcoin/bitcoin.hpp
include/bitcoin/bitcoin/config/block.hpp
src/config/block.cpp
test/config/block.cpp

The first intended use of this class is deserializing the genesis block.

add config::block class.

---

include/bitcoin/bitcoin/settings.hpp
src/chain/chain_state.cpp
src/chain/header.cpp
src/settings.cpp

settings::work_limit() doesn't really fit the settings class. Because it's effectively used only once it can be inlined.

eliminate settings::work_limit()

---

include/bitcoin/bitcoin/config/block.hpp
src/config/block.cpp
test/config/block.cpp

This is the last bit needed to make `config::block` work using `boost::program_options`. It's necessary to implement the copy assignment explicitly because the copy assignment operator for `chain::block`, which is its internal type, has been deleted.

Add copy assignment operator for config::block.

---

src/chain/transaction.cpp

if not defined NDEBUG is a double negative. prior builds have never excluded `put.script().operations();` and I don't know what the implications are, if any, of fixing this typo and therefore (correctly) excluding this call to do put.script() when NDEBUG is defined.

NDBEUG typo

---

src/chain/block.cpp

if anyone had ever tried to retrieve witness data with block.to_data(true) it wouldn't have included witness data. now it does.

witness param supported in to_data(witness)

---

include/bitcoin/bitcoin/math/ec_scalar.hpp
src/math/ec_scalar.cpp
test/math/ec_point.cpp
test/math/ec_scalar.cpp

As the title says.
non-const accessor is needed to be able to modify underlying secret value without unecessary copying.
construct by value is very useful for doing calculations where we blind output amounts (for example).
Also the unit test filenames for ec_point and ec_scalar were reversed. I switched them over.

ec_scalar: add non-const accessor and construct by value

---

include/bitcoin/bitcoin/impl/utility/deserializer.ipp
include/bitcoin/bitcoin/impl/utility/serializer.ipp

Constructor initialization of variables should follow layout in class definition otherwise compiler gives warnings when set in strict compile modes such as -Wall

-Wreorder gives warnings about order of initialization.

---

src/unicode/unicode.cpp

Previous implementation doesn't detect missing ICU. boost:normalize fails silently without ICU.

Verifier of backend manager was improved.

---

include/bitcoin/system/wallet/payment_address.hpp
src/wallet/payment_address.cpp

@evoskuil I think something like this will help simplify generating the output index hashes.  It's also directly applicable to a command like `script-from-address` (in bx).  Thoughts?

Add a method to return the output script from a payment address.

---

README.md

Coveralls referenced the old libbitcoin repository.

Coveralls status fix

---

include/bitcoin/system/chain/block.hpp
src/chain/block.cpp

Remove: Redundant member initializer in constructor initialization list.
https://clang.llvm.org/extra/clang-tidy/checks/readability-redundant-member-init.html
Remove: std::move has no effect (trivially copyable)
https://clang.llvm.org/extra/clang-tidy/checks/performance-move-const-arg.html
Remove: Redundant qualifier
Remove: Redundant else
Remove: Unused include
Add: const
Change: Hide warning "using the result of an assignment as a condition" through parenthesis.

Multiple small changes in block (redudant code, const etc.)

---

Makefile.am
builds/cmake/CMakeLists.txt
builds/msvc/vs2013/libbitcoin-system-test/libbitcoin-system-test.vcxproj
builds/msvc/vs2013/libbitcoin-system-test/libbitcoin-system-test.vcxproj.filters
builds/msvc/vs2013/libbitcoin-system/libbitcoin-system.vcxproj
builds/msvc/vs2013/libbitcoin-system/libbitcoin-system.vcxproj.filters
builds/msvc/vs2015/libbitcoin-system-test/libbitcoin-system-test.vcxproj
builds/msvc/vs2015/libbitcoin-system-test/libbitcoin-system-test.vcxproj.filters
builds/msvc/vs2015/libbitcoin-system/libbitcoin-system.vcxproj
builds/msvc/vs2015/libbitcoin-system/libbitcoin-system.vcxproj.filters
builds/msvc/vs2017/libbitcoin-system-test/libbitcoin-system-test.vcxproj
builds/msvc/vs2017/libbitcoin-system-test/libbitcoin-system-test.vcxproj.filters
builds/msvc/vs2017/libbitcoin-system/libbitcoin-system.vcxproj
builds/msvc/vs2017/libbitcoin-system/libbitcoin-system.vcxproj.filters
include/bitcoin/system.hpp
include/bitcoin/system/chain/script.hpp
include/bitcoin/system/wallet/payment_address.hpp
include/bitcoin/system/wallet/witness_address.hpp
src/chain/script.cpp
src/formats/base_32.cpp
src/wallet/witness_address.cpp
test/wallet/witness_address.cpp

Add payment address parsing and tests for standard witness scripts, including address formats specified in BIP 142 and BIP 173 (v0 only).
Resolves #844

Add payment address parsing and tests for standard witness scripts

---

include/bitcoin/system/utility/timer.hpp

This code is not needed, since the std::forward optimizes out the intervening function call and the result is exactly similar.

Remove duplicate code in timer

---

README.md

Current version of gcc is 9.3... even Debian stable which has very old software uses gcc 6.3 now. I think it's safe to remove these instructions now.

remove instructions about old version of gcc 4.8

---

include/bitcoin/system/math/ec_scalar.hpp
src/math/ec_scalar.cpp
test/math/ec_scalar.cpp

* Removes assertions that are provably unreachable.
* Eliminates use of the `new` operator.
* Eliminates unused type (`using`) definition.
* Reorganizes and comments method order more closely to lib conventions.
* Expands to full unit test coverage.
* Changes the negation operator to non-`const` (as it modifies the operand).
* Changes the binary math operators so that they retain expected `const`-ness (operands should not be modified).
For optimal performance the binary math operators `+`, `-` and `*` should be avoided as they create copies, due to the nature of the libsecp256k1 functions.
For optimal performance subtraction assignment `-=` should be avoided, as there is no subtraction function in libsecp256k1, resulting in a copy to avoid `const` operand modification.
The math assignment …

 Don't modify const, normalize math ops, add test cases, style.

---

.travis.yml

This fixes a build break triggered by `brew update` but caused by a change to the underlying Travis platform. The update isn't required in the static macOS build.

Remove brew update from .yml where not required.

---

src/unicode/unicode.cpp

We avoid exceptions except in the case of operating inside of a stream.

Convert debug asserts to exceptions in unsafe exported stream functions.

---

include/bitcoin/system/wallet/electrum.hpp
src/wallet/electrum.cpp
test/wallet/electrum.cpp

Validation is now as follows: Provided a word list and a starting entropy value, it is possible to create a new mnemonic, which should match the provided word list.
There are a couple electrum test cases that do not provide the original entropy, so we don't validate those.  Many more electrum test cases do provide the entropy, so those are now properly validated.

Fixes electrum mnemonic validation by requiring the initial entropy.

---

include/bitcoin/system/wallet/dictionary.hpp

bunch of compile errors for dictionary.hpp. Simple fix, missing header

missing include for size_t on linux

---

include/bitcoin/system/hash/accumulator.hpp
src/hash/accumulator.cpp

This saves another MB on library and test executable.

Explicitly initialize accumulator sha512

---

include/bitcoin/system/define.hpp
include/bitcoin/system/have.hpp
include/bitcoin/system/impl/hash/sha/algorithm.ipp
include/bitcoin/system/warnings.hpp
test/hash/performance/performance.hpp

Also updating platform s++20 support defines.

Avoid tautological compare warn by compilers w/o vector constexpr.

---

include/bitcoin/system/wallet/keys/hd_private.hpp

Fixes issue #1625 by-value operator= conflict

Removed by-value operator= from hd_private

---

src/config/utilities.cpp
src/unicode/utf8_everywhere/stdio.cpp

Updated IPv6 to IPv4 conversion to avoid deprecated Boost methods and implemented manual byte extraction. Refactored console echo functions to use termios on non-Windows platforms and added stubs for Windows, improving cross-platform compatibility.

Refactor IPv6/IPv4 handling and console echo logic
