- include/bitcoin/bitcoin/stealth.hpp
- src/network/protocol.cpp
update list of seed nodes for testnet
> update list of seed nodes for testnet.

- include/bitcoin/bitcoin/network/channel.hpp
- src/network/channel.cpp
Reverts libbitcoin/libbitcoin#178
> Revert "Fix race condition in channel"

- include/bitcoin/bitcoin/network/channel.hpp
- src/network/channel.cpp
Instead of using a mutex. I instead use the strand. This seems to work better.
> remove the mutex, use the strand instead.

- src/script.cpp
- test/script.cpp
this mistake was my error. I've added a unit test to catch this edge case.
> correct one_hash which was backwards due to difference with how hashes look and how they are.

- .travis.yml
- README.md
- builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.props
- builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj
- builds/msvc/vs2013/libbitcoin-test/packages.config
- builds/msvc/vs2013/libbitcoin/libbitcoin.props
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
- builds/msvc/vs2013/libbitcoin/packages.config
- configure.ac
- install.sh
- libbitcoin.pc.in
- src/math/ec_keys.cpp
- test/ec_keys.cpp
Note that this (temporarily) disables non-deterministic signature capability.
> Integrate latest secp256k1 and drop GMP.

- examples/main.cpp
- include/bitcoin/bitcoin/utility/unicode.hpp
- include/bitcoin/bitcoin/utility/unicode_streambuf.hpp
- src/utility/unicode.cpp
- src/utility/unicode_streambuf.cpp
Improve readability, publish array-based converters, optimize character split detection.
> Refactor unicode_streambuf.

- include/bitcoin/bitcoin/define.hpp
- include/bitcoin/bitcoin/unicode/unicode.hpp
- src/unicode/unicode.cpp
explorer doesn't build against version2 after recent changes.  these are the minimal changes needed to get it building again.
> - pull in necessary changes from master to allow explorer to build

- include/bitcoin/bitcoin/config/authority.hpp
- include/bitcoin/bitcoin/constants.hpp
- include/bitcoin/bitcoin/impl/serialize/misc.ipp
- include/bitcoin/bitcoin/network/acceptor.hpp
- include/bitcoin/bitcoin/network/channel.hpp
- include/bitcoin/bitcoin/network/channel_proxy.hpp
- include/bitcoin/bitcoin/network/handshake.hpp
- include/bitcoin/bitcoin/network/protocol.hpp
- include/bitcoin/bitcoin/network/settings.hpp
- include/bitcoin/bitcoin/primitives.hpp
- src/error.cpp
- src/network/acceptor.cpp
- src/network/channel.cpp
- src/network/channel_proxy.cpp
- src/network/connect_with_timeout.cpp
- src/network/connect_with_timeout.hpp
- src/network/handshake.cpp
- src/network/protocol.cpp
- src/network/seeder.cpp
- src/satoshi_serialize.cpp
Fixes: https://github.com/libbitcoin/libbitcoin/issues/283
> Fix handshake races, support ping/pong, config self ip address.

- Makefile.am
- builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj
- builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj.filters
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
- include/bitcoin/bitcoin.hpp
- include/bitcoin/bitcoin/wallet/bitcoin_uri.hpp
- include/bitcoin/bitcoin/wallet/uri.hpp
- src/wallet/bitcoin_uri.cpp
- src/wallet/uri.cpp
- test/wallet/bitcoin_uri.cpp
- test/wallet/uri.cpp
This exists to help with BitID and other things of that nature. The code works, and I've tried to stick to the latest coding standards, but this could probably use good solid review before accepting.
> New general-purpose URI parsing module

- src/chain/operation.cpp
> - fixes regression in logic flow through operation deserialization

- src/script.cpp
> No reparse sig in multisig test in non-strict context; inverted test.

- src/chain/block.cpp
- src/chain/input.cpp
- src/chain/operation.cpp
- src/chain/output.cpp
- src/chain/point.cpp
- src/chain/transaction.cpp
- src/config/printer.cpp
- src/message/address.cpp
- src/message/alert.cpp
- src/message/filter_add.cpp
- src/message/filter_load.cpp
- src/message/headers.cpp
- src/message/inventory.cpp
- src/message/inventory_vector.cpp
- src/message/merkle_block.cpp
- src/message/version.cpp
- src/wallet/hd_private.cpp
- src/wallet/parse_encrypted_keys/parse_encrypted_prefix.hpp
- src/wallet/parse_encrypted_keys/parse_encrypted_private.hpp
- src/wallet/parse_encrypted_keys/parse_encrypted_public.hpp
- src/wallet/parse_encrypted_keys/parse_encrypted_token.hpp
This set of changes addresses a bunch of style/performance warnings emitted by cppcheck on the current master branch.
> Fix minor style / performance issues

- include/bitcoin/bitcoin/utility/binary.hpp
- include/bitcoin/bitcoin/wallet/address.hpp
- install.sh
- src/utility/binary.cpp
- src/wallet/address.cpp
Thanks to @mlmikael for testing OpenBSD support!
> Make binary and address sortable, add openbsd installer support.

- Doxyfile
The Doxyfile seems to be one that has just been forgotten about.  Changes make Doxygen recurse so even if the file continues to be ignored new directories will be incorporated into the generated documentation.
> Updated Doxygen file to generate docs

- Makefile.am
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
- include/bitcoin/bitcoin.hpp
- include/bitcoin/bitcoin/impl/utility/notifier.ipp
- include/bitcoin/bitcoin/impl/utility/resubscriber.ipp
- include/bitcoin/bitcoin/impl/utility/subscriber.ipp
- include/bitcoin/bitcoin/utility/asio.hpp
- include/bitcoin/bitcoin/utility/binary.hpp
- include/bitcoin/bitcoin/utility/notifier.hpp
- include/bitcoin/bitcoin/utility/random.hpp
- include/bitcoin/bitcoin/utility/resubscriber.hpp
- include/bitcoin/bitcoin/utility/subscriber.hpp
- include/bitcoin/bitcoin/utility/timer.hpp
- src/utility/binary.cpp
- src/utility/random.cpp
- test/utility/random.cpp
This set of updates supports the new libbitcoin-server subscription implementation.
> Add notifier, improve subscriber safety, use std::chrono.

- src/chain/point.cpp
https://github.com/libbitcoin/libbitcoin-server/issues/245
> Revert point::checksum change due to server API compat break.

- include/bitcoin/bitcoin/constants.hpp
- include/bitcoin/bitcoin/message/network_address.hpp
- include/bitcoin/bitcoin/message/version.hpp
- test/config/authority.cpp
> Add bip64 and bip111 ver levels, refactor for svcs bit.

- include/bitcoin/bitcoin/chain/header.hpp
- include/bitcoin/bitcoin/message/header_message.hpp
- include/bitcoin/bitcoin/message/headers.hpp
- include/bitcoin/bitcoin/message/merkle_block.hpp
- src/chain/block.cpp
- src/chain/header.cpp
- src/message/compact_block.cpp
- src/message/header_message.cpp
- src/message/headers.cpp
- src/message/merkle_block.cpp
- test/chain/block.cpp
- test/chain/header.cpp
- test/message/block_message.cpp
- test/message/header_message.cpp
- test/message/headers.cpp
- test/message/merkle_block.cpp
> Remove transaction count from header.

- src/chain/script/operation.cpp
- src/chain/script/script.cpp
Comment Typo fix
Related to https://github.com/libbitcoin/libbitcoin-explorer/pull/399
> Fix instance of potential operation access before operation cache load

- include/bitcoin/bitcoin/wallet/select_outputs.hpp
- src/wallet/select_outputs.cpp
Adds the individual algorithm for utxo selection, which allows selection of all utxos available that can individually satisfy the amount requested.
> Adds the individual algorithm for utxo selection, which allows

- install.sh
> Replaces zlib URL with github

- include/bitcoin/bitcoin/constants.hpp
- src/chain/block.cpp
- src/chain/script.cpp
- src/chain/transaction.cpp
- src/machine/operation.cpp
- src/message/address.cpp
- src/message/block_transactions.cpp
- src/message/compact_block.cpp
- src/message/filter_add.cpp
- src/message/filter_load.cpp
- src/message/get_block_transactions.cpp
- src/message/get_blocks.cpp
- src/message/headers.cpp
- src/message/inventory.cpp
- src/message/merkle_block.cpp
Resolves https://github.com/libbitcoin/libbitcoin/issues/720
> Guard against excess message preallocation during read.

- include/bitcoin/bitcoin/impl/machine/interpreter.ipp
- include/bitcoin/bitcoin/impl/machine/program.ipp
Removes compiler warnings (unused variables) and signed/unsigned comparison
> Removes compiler warnings

- src/chain/script.cpp
Back-ported from master, deserialization fix.
> Fix over-constrained memory guard on script (consensus).

- include/bitcoin/bitcoin/utility/thread.hpp
https://github.com/libbitcoin/libbitcoin/issues/733
> Backport fix to thread local storage boost issue.

- include/bitcoin/bitcoin/chain/output.hpp
- src/chain/output.cpp
Allow version information when converting from script to payment address
> Allow version information when converting from script

- src/chain/script.cpp
- src/wallet/payment_address.cpp
- test/chain/script.cpp
See: https://github.com/libbitcoin/libbitcoin/issues/814
> Updates to multisig pattern fix, enable extraction.

- include/bitcoin/bitcoin/chain/script.hpp
- include/bitcoin/bitcoin/impl/machine/interpreter.ipp
- include/bitcoin/bitcoin/impl/machine/operation.ipp
- include/bitcoin/bitcoin/math/elliptic_curve.hpp
- src/chain/script.cpp
- src/math/elliptic_curve.cpp
- src/wallet/payment_address.cpp
- test/chain/script.cpp
This revises script address extraction and adds detailed comments regarding the limitations of context-free address extraction from input scripts.
See also: https://github.com/libbitcoin/libbitcoin/pull/826
> Backport: Revise script address extraction. 

- include/bitcoin/bitcoin/chain/block.hpp
- include/bitcoin/bitcoin/error.hpp
- src/chain/block.cpp
- src/chain/transaction.cpp
- src/error.cpp
- test/chain/block.cpp
Resolves: https://github.com/libbitcoin/libbitcoin/issues/834
> Consensus: impose partial order on block transactions.

- include/bitcoin/bitcoin/chain/input.hpp
- include/bitcoin/bitcoin/chain/output.hpp
- include/bitcoin/bitcoin/wallet/payment_address.hpp
- src/chain/input.cpp
- src/chain/output.cpp
- src/wallet/payment_address.cpp
This is a master backport to resolve server indexing issue.
> Allow multiple payment addresses per parsed script.

- include/bitcoin/bitcoin/wallet/encrypted_keys.hpp
https://github.com/libbitcoin/libbitcoin/issues/885
> Fix misaligned WITH_ICU exclusions.

- src/utility/png.cpp
Error not detected by the unit tests
> undefined behavior fixed

- Makefile.am
- include/bitcoin/bitcoin.hpp
- include/bitcoin/bitcoin/formats/base_32.hpp
- src/formats/base_32.cpp
- test/formats/base_32.cpp
The new files add bech32 encoding/decoding for data chunks according to bip173.
> Added base32

- Makefile.am
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj
- builds/msvc/vs2013/libbitcoin/libbitcoin.vcxproj.filters
- builds/msvc/vs2015/libbitcoin/libbitcoin.vcxproj
- builds/msvc/vs2015/libbitcoin/libbitcoin.vcxproj.filters
- builds/msvc/vs2017/libbitcoin/libbitcoin.vcxproj
- builds/msvc/vs2017/libbitcoin/libbitcoin.vcxproj.filters
- include/bitcoin/bitcoin.hpp
- include/bitcoin/bitcoin/config/header.hpp
- include/bitcoin/bitcoin/config/input.hpp
- include/bitcoin/bitcoin/config/output.hpp
- include/bitcoin/bitcoin/config/point.hpp
- include/bitcoin/bitcoin/config/transaction.hpp
- include/bitcoin/bitcoin/constants.hpp
- include/bitcoin/bitcoin/define.hpp
- include/bitcoin/bitcoin/impl/utility/property_tree.ipp
- include/bitcoin/bitcoin/impl/utility/string.ipp
- include/bitcoin/bitcoin/utility/property_tree.hpp
- include/bitcoin/bitcoin/utility/string.hpp
- src/config/header.cpp
- src/config/input.cpp
- src/config/output.cpp
- src/config/point.cpp
- src/config/transaction.cpp
- src/utility/property_tree.cpp
Move some common explorer config classes and prop_tree methods into core as property_tree
> Move some common explorer config classes into system

- src/chain/block.cpp
- test/chain/block.cpp
Style (trailing space removal)
Add a unit test for this case (resolved after #953)
> Style and adds unit test

- Makefile.am
- include/bitcoin/bitcoin/config/endpoint.hpp
- include/bitcoin/bitcoin/utility/property_tree.hpp
- src/config/endpoint.cpp
- src/utility/property_tree.cpp
- test/config/endpoint.cpp
- test/utility/property_tree.cpp
Move/Add additional functionality to bc::property_tree, including a unit test for json to property conversion.
> Move/Add additional functionality to bc::property_tree

- builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj
- builds/msvc/vs2013/libbitcoin-test/libbitcoin-test.vcxproj.filters
- builds/msvc/vs2015/libbitcoin-test/libbitcoin-test.vcxproj
- builds/msvc/vs2015/libbitcoin-test/libbitcoin-test.vcxproj.filters
- builds/msvc/vs2017/libbitcoin-test/libbitcoin-test.vcxproj
- builds/msvc/vs2017/libbitcoin-test/libbitcoin-test.vcxproj.filters
- install.sh
Addresses branch change for secp256k1
> Regenerate artifacts.

- include/bitcoin/bitcoin/config/script.hpp
- src/config/script.cpp
Related to https://github.com/libbitcoin/libbitcoin-explorer/issues/541
> Optionally allow flags to be specified on config/script

- include/bitcoin/bitcoin/error.hpp
- include/bitcoin/bitcoin/impl/machine/interpreter.ipp
- src/chain/script.cpp
- src/error.cpp
DO NOT MERGE UNTIL FULLY VERIFIED
Backported from master, see: https://github.com/libbitcoin/libbitcoin-client/issues/240
>  Simplify bip66 behavior, fix multisig.

- include/bitcoin/bitcoin/error.hpp
- include/bitcoin/bitcoin/impl/machine/interpreter.ipp
- include/bitcoin/bitcoin/math/elliptic_curve.hpp
- src/chain/script.cpp
- src/error.cpp
- src/math/elliptic_curve.cpp
- test/chain/script.cpp
See: https://github.com/libbitcoin/libbitcoin/issues/1055
> Simplify bip66 behavior, fix multisig.

- include/bitcoin/bitcoin/wallet/ec_private.hpp
Hi. Just to fix a simple typo that I found while using libbitcoin. Thanks.
> Fix a simple typo

- include/bitcoin/bitcoin/math/ec_scalar.hpp
- src/math/ec_scalar.cpp
- test/math/ec_point.cpp
- test/math/ec_scalar.cpp
See previous review comments: https://github.com/libbitcoin/libbitcoin/pull/1080
This also unreverts the fix to reversed test file names (thanks @narodnik).
> Revert pushed commits for further discussion.

- include/bitcoin/system/chain/transaction.hpp
Ref: libbitcoin/libbitcoin-blockchain#498
> Add cataloged to transaction metadata

- README.md
The build status was not displayed correctly.
> Build status fix

- include/bitcoin/system/chain/block.hpp
- include/bitcoin/system/machine/rule_fork.hpp
- src/chain/block.cpp
- src/chain/chain_state.cpp
- src/chain/header.cpp
- src/chain/transaction.cpp
- test/machine/opcode.cpp
This will require a database resync as the fork enumeration has changed.
> Implement bip42 soft fork (finite monetary supply).

- include/bitcoin/system/math/hash.hpp
- src/math/hash.cpp
- test/math/hash.cpp
- test/math/hash.hpp
> Add pbkdf2_hmac_sha256 function to the public API

- include/bitcoin/system/impl/machine/interpreter.ipp
- include/bitcoin/system/machine/interpreter.hpp
A simple PR to stop repeating ourselves on the code to handle the witness program.
> DRY up repeated code for connecting witness txs

- include/bitcoin/system/impl/machine/interpreter.ipp
- include/bitcoin/system/machine/interpreter.hpp
This PR moves code that handles connecting p2sh into a separate function.
Let me know if these changes potentially break anything, I can add new tests to be sure we don't break anything.
> Refactor connecting p2sh into a separate method

- README.md
nit
I think it was missed by ced2cfa9ba4780d25f5b302fb32716f1d6d5e235
> update README: rename Macintosh to macOS

- src/wallet/keys/hd_private.cpp
- test/wallet/keys/hd_private.cpp
- test/wallet/keys/hd_public.cpp
Rebased, style corrections, squashed commits.
> Guard deriving public from invalid extended private key, update tests.
